Repository MijeongJeon/good_git_study, pull requests merged in 2019-03, with the labels that each got.

#2 Add book_recommand(#1)
  book_recommand.md
Labels: 문서화

#4 진우의 서적 2권 추가(#1)
  book_recommand.md
Labels: 문서화

#5 다연의 서적 추천 (#1)
  book_recommand.md
Labels: 문서화

#7 파이썬 개발 서적 추천 추가(#1)
  book_recommand.md
Labels: 문서화

#10 진우의 개발 서적 추천 (#1)
  book_recommand.md
Labels: 문서화

#21 git 기본 명령어 파일 생성/add 명령어 정리(#20)
  basic_git_commands.md
Labels: git 기본 명령어

#22 README 파일에 프로필 이미지 업로드 (#11)
  README.md
Labels: good first issue, 중요

#23 기본명령어 checkout 정보 추가 (#14)
  basic_git_commands.md
Labels: git 기본 명령어, 문서화
